# Generated by Django 4.2.2 on 2023-07-10 10:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('prodhouse', '0006_slave_detail_slave_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slave',
            old_name='detail',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='slave',
            old_name='role',
            new_name='exp',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='link',
            field=models.URLField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='slave',
            name='fb_id',
            field=models.URLField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='slave',
            name='insta_id',
            field=models.URLField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='slave',
            name='linkedin_url',
            field=models.URLField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='project_type',
            field=models.CharField(choices=[('VFX', 'VFX'), ('Digital Art', 'Digital Art'), ('Games', 'Games')], default='past', max_length=300),
        ),
    ]
