# Generated by Django 4.2.2 on 2023-07-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodhouse', '0007_rename_detail_slave_bio_rename_role_slave_exp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/img/')),
            ],
        ),
    ]
